### ISSUE TITLE
how to make a differential drive mobile robot follow a curved path?

### ISSUE THREAD

**Issue by arenas7307979** [cogsys-tuebingen/gerona#21]
hii, My current setup is a skid-steer drive mobile base which takes command velocity. 
I got robot pose and path( collision free trajectory ),  and now i need a path-following controller ( cml_vel)  to make the skid-steer robot to follow the concern trajectory 
So it there any good example or module that i can use directly?
It looks like this description, but I don't understand the detailed operation

![image](https://user-images.githubusercontent.com/5019568/73428549-8384b080-4374-11ea-9343-ce564bf7c252.png)

**Comment by betwo** [comment]
Hey @arenas7307979, I created a new example (`gerona_examples/launch/gazebo_example_pioneer_follower_only.launch`).
There, only the path follower is used, together with a high level, Python script that uses the action lib API: `gerona_examples/src/follow_path_example.py`

I hope this helps you out, if not please re-open this issue again!

**Comment by arenas7307979** [comment]
I appreciate your help very much

**Comment by arenas7307979** [comment]
hii, betwo
I try to use gazebo_example_pioneer_follower_only example. launch
But when I specify the reverse path, the path follower goes in the opposite direction until it hits the wall

![圖片](https://user-images.githubusercontent.com/5019568/74175001-f7c22c80-4c6f-11ea-894c-35cca7544327.png)

**Comment by betwo** [comment]
The problem is that `global_planner` (http://wiki.ros.org/global_planner) does not respect the kinematics of the robot.
This example is meant to only show how to use the path follower from GeRoNa without using our path planner.

What can be done is using the [local planner](https://github.com/cogsys-tuebingen/gerona/wiki/Local-Planner) feature of the path follower, I have created an issue for that in #24 .

Unfortunately, I currently have little spare time, so it might take a few days for me to work on this.
If you want you can try modifying the example yourself by setting
```xml
    <param name="path_follower/local_planner/algorithm" value="AStar" />
```
and tweaking the parameters until you get better behaviour.

**Comment by arenas7307979** [comment]
Ok, I'll try to adjust the parameters and try to work with my global planner
Thanks for your help * 2

**Comment by arenas7307979** [comment]
hii, betwo 
I've been studying gazebo_example_pioneer_follower_only.launch
have few questions about path control, 
(According to wiki description,  user can communicate only with path_control without sending any messages directly to path_planner or path_follower)

However, path control seems like an unnecessary module in example follower_only.launch
follow_path_example.py(high dummy level) can direct communicate with path_follower by msg of action
